"""Bake the trained PINN weights into a C++ header.

The model is a small MLP s -> mu with architecture:
    Linear(1, H) -> Tanh -> Linear(H, H) -> Tanh -> Linear(H, 1) -> 1.2 * sigmoid

This script reads `models/pinn_mu.pth` and writes
`cpp/include/vd/pinn_weights.h` containing the weights and biases as
`constexpr double` arrays plus the hidden width. The C++ forward pass in
`cpp/include/vd/pinn.hpp` includes this header directly, so the binary
embeds the model — no file I/O, no external dependencies at run time.
"""

from __future__ import annotations

import argparse
import os
import sys

import torch

# Re-import the MuNet class so we can load the state_dict cleanly.
sys.path.insert(0, os.path.dirname(os.path.dirname(__file__)))
from src.ml.pinn import MuNet  # noqa: E402


def _emit_array(name: str, arr, rows: int, cols: int, file) -> None:
    file.write(f"constexpr double {name}[{rows * cols}] = {{\n")
    flat = arr.flatten().tolist()
    for i in range(0, len(flat), 8):
        chunk = flat[i:i + 8]
        file.write("    " + ", ".join(f"{v: .9e}" for v in chunk) + ",\n")
    file.write("};\n\n")


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--in", dest="src", default="models/pinn_mu.pth")
    ap.add_argument("--out", default="cpp/include/vd/pinn_weights.h")
    ap.add_argument("--hidden", type=int, default=32)
    args = ap.parse_args()

    net = MuNet(hidden=args.hidden)
    state = torch.load(args.src, map_location="cpu", weights_only=True)
    net.load_state_dict(state)
    net.eval()

    # The Sequential layer order: [Linear, Tanh, Linear, Tanh, Linear]
    layers = [m for m in net.net if isinstance(m, torch.nn.Linear)]
    assert len(layers) == 3, f"expected 3 Linear layers, got {len(layers)}"

    W1 = layers[0].weight.detach().numpy()  # (H, 1)
    b1 = layers[0].bias.detach().numpy()    # (H,)
    W2 = layers[1].weight.detach().numpy()  # (H, H)
    b2 = layers[1].bias.detach().numpy()    # (H,)
    W3 = layers[2].weight.detach().numpy()  # (1, H)
    b3 = layers[2].bias.detach().numpy()    # (1,)

    H = args.hidden
    assert W1.shape == (H, 1)
    assert W2.shape == (H, H)
    assert W3.shape == (1, H)

    os.makedirs(os.path.dirname(args.out), exist_ok=True)
    with open(args.out, "w", newline="\n") as f:
        f.write("// Auto-generated by tools/export_weights.py. Do not edit by hand.\n")
        f.write("// Source: models/pinn_mu.pth\n")
        f.write("#pragma once\n\n")
        f.write("namespace vd::pinn_weights {\n\n")
        f.write(f"constexpr int kHidden = {H};\n\n")
        _emit_array("W1", W1, H, 1, f)
        _emit_array("b1", b1, H, 1, f)
        _emit_array("W2", W2, H, H, f)
        _emit_array("b2", b2, H, 1, f)
        _emit_array("W3", W3, 1, H, f)
        _emit_array("b3", b3, 1, 1, f)
        f.write("}  // namespace vd::pinn_weights\n")

    print(f"wrote {args.out}  (Linear 1->{H} -> {H}->{H} -> {H}->1, total params "
          f"{W1.size + b1.size + W2.size + b2.size + W3.size + b3.size})")


if __name__ == "__main__":
    main()
